name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make libgtest-dev

    - name: Create build directory
      run: mkdir -p build

    - name: Configure project
      working-directory: build
      run: cmake ..

    - name: Build project
      working-directory: build
      run: make

    - name: Run tests
      working-directory: build
      run: ./tests

    - name: Clean build directory
      run: make cleanall