name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev cmake

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        ./build/tests